### PR TITLE
Clean up this code mess

### PR DESCRIPTION
**Pull request by mdoryammilwalrus**
This has gotten pretty messy from when me and gage created it...

### CODE REVIEW

**Comment by liutristan** [comment]
i need the google analytics tags

**Comment by liutristan** [comment]
and the ad tags

**Comment by liutristan** [comment]
and were not a fork of amethyst

**Comment by liutristan** [comment]
gage made amythyst

**Comment by liutristan** [comment]
and i wanna keep loading animation

**Comment by mdoryammilwalrus** [comment]
The loading animation makes it looks so slow that it needs one

Also gage _and_ me made amethyst, so quit saying that I did not

**Comment by mdoryammilwalrus** [comment]
@liutristan

**Comment by oHeckGage** [comment]
the only reason it is messy is because I'm too lazy to put it into a beautifier and tristan and other devs put all sorts of copy pasted imports and shit

**Pull request closed without merging**
